# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from griffin_python_sdk.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    V0_INDEX = "/v0/index"
    V0_PING = "/v0/ping"
    V0_ADMISSIONS_ADMISSIONID = "/v0/admissions/{admission-id}"
    V0_APIKEYS_APIKEYID = "/v0/api-keys/{api-key-id}"
    V0_BANK_ACCOUNTS_BANKACCOUNTID = "/v0/bank/accounts/{bank-account-id}"
    V0_BANK_ACCOUNTS_BANKACCOUNTID_ACTIONS_CLOSE = "/v0/bank/accounts/{bank-account-id}/actions/close"
    V0_BANK_ACCOUNTS_BANKACCOUNTID_ADMISSIONS = "/v0/bank/accounts/{bank-account-id}/admissions"
    V0_BANK_ACCOUNTS_BANKACCOUNTID_MEMBERSHIP = "/v0/bank/accounts/{bank-account-id}/membership"
    V0_BANK_ACCOUNTS_BANKACCOUNTID_MEMBERSHIPUPDATES = "/v0/bank/accounts/{bank-account-id}/membership-updates"
    V0_BANK_ACCOUNTS_BANKACCOUNTID_PAYMENTS = "/v0/bank/accounts/{bank-account-id}/payments"
    V0_BANK_ACCOUNTS_BANKACCOUNTID_SUBMISSIONS = "/v0/bank/accounts/{bank-account-id}/submissions"
    V0_BANK_ACCOUNTS_BANKACCOUNTID_TRANSACTIONS = "/v0/bank/accounts/{bank-account-id}/transactions"
    V0_BANK_TRANSACTIONS_TRANSACTIONID = "/v0/bank/transactions/{transaction-id}"
    V0_COMPANIESHOUSE_COMPANIES_COMPANYNUMBER = "/v0/companies-house/companies/{company-number}"
    V0_EVENTS_EVENTID = "/v0/events/{event-id}"
    V0_LEGALPERSONS_LEGALPERSONID = "/v0/legal-persons/{legal-person-id}"
    V0_LEGALPERSONS_LEGALPERSONID_BANK_PAYEES = "/v0/legal-persons/{legal-person-id}/bank/payees"
    V0_LEGALPERSONS_LEGALPERSONID_CLAIMS = "/v0/legal-persons/{legal-person-id}/claims"
    V0_LEGALPERSONS_LEGALPERSONID_DECISIONS = "/v0/legal-persons/{legal-person-id}/decisions"
    V0_LEGALPERSONS_LEGALPERSONID_HISTORY = "/v0/legal-persons/{legal-person-id}/history"
    V0_LEGALPERSONS_LEGALPERSONID_VERIFICATIONS = "/v0/legal-persons/{legal-person-id}/verifications"
    V0_MEMBERSHIPS_MEMBERSHIPID = "/v0/memberships/{membership-id}"
    V0_MEMBERSHIPS_MEMBERSHIPID_ROLES = "/v0/memberships/{membership-id}/roles"
    V0_ONBOARDING_APPLICATIONS_ONBOARDINGAPPLICATIONID = "/v0/onboarding/applications/{onboarding-application-id}"
    V0_ORGANIZATIONS_ORGANIZATIONID = "/v0/organizations/{organization-id}"
    V0_ORGANIZATIONS_ORGANIZATIONID_APIKEYS = "/v0/organizations/{organization-id}/api-keys"
    V0_ORGANIZATIONS_ORGANIZATIONID_BANK_ACCOUNTS = "/v0/organizations/{organization-id}/bank/accounts"
    V0_ORGANIZATIONS_ORGANIZATIONID_EVENTS = "/v0/organizations/{organization-id}/events"
    V0_ORGANIZATIONS_ORGANIZATIONID_INVITATIONS = "/v0/organizations/{organization-id}/invitations"
    V0_ORGANIZATIONS_ORGANIZATIONID_LEGALPERSONS = "/v0/organizations/{organization-id}/legal-persons"
    V0_ORGANIZATIONS_ORGANIZATIONID_MEMBERSHIPS = "/v0/organizations/{organization-id}/memberships"
    V0_ORGANIZATIONS_ORGANIZATIONID_ONBOARDING_APPLICATIONS = "/v0/organizations/{organization-id}/onboarding/applications"
    V0_ORGANIZATIONS_ORGANIZATIONID_WEBHOOKS = "/v0/organizations/{organization-id}/webhooks"
    V0_ORGANIZATIONS_ORGANIZATIONID_WORKFLOWS = "/v0/organizations/{organization-id}/workflows"
    V0_PAYEES_PAYEEID = "/v0/payees/{payee-id}"
    V0_PAYMENTS_PAYMENTID = "/v0/payments/{payment-id}"
    V0_PAYMENTS_PAYMENTID_ADMISSIONS = "/v0/payments/{payment-id}/admissions"
    V0_PAYMENTS_PAYMENTID_SUBMISSIONS = "/v0/payments/{payment-id}/submissions"
    V0_ROLES = "/v0/roles"
    V0_ROLES_ROLEID = "/v0/roles/{role-id}"
    V0_SUBMISSIONS_SUBMISSIONID = "/v0/submissions/{submission-id}"
    V0_USERS_USERID = "/v0/users/{user-id}"
    V0_USERS_USERID_APIKEYS = "/v0/users/{user-id}/api-keys"
    V0_USERS_USERID_MEMBERSHIPS = "/v0/users/{user-id}/memberships"
    V0_VERIFICATIONS_VERIFICATIONID = "/v0/verifications/{verification-id}"
    V0_WEBHOOKS_WEBHOOKID = "/v0/webhooks/{webhook-id}"
    V0_WEBHOOKS_WEBHOOKID_ACTIONS_ACTIVATE = "/v0/webhooks/{webhook-id}/actions/activate"
    V0_WEBHOOKS_WEBHOOKID_ACTIONS_DEACTIVATE = "/v0/webhooks/{webhook-id}/actions/deactivate"
    V0_WEBHOOKS_WEBHOOKID_ACTIONS_TEST = "/v0/webhooks/{webhook-id}/actions/test"
    V0_WORKFLOWS_WORKFLOWID = "/v0/workflows/{workflow-id}"
